[build]
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_SITE_NAME = "TGP2025 – Training Graduate Program"
  NEXT_PUBLIC_SITE_URL = "https://future-tech.ly/tgp2025"

[build.processing]
  skip_processing = false

